![GitHub Community GITAM](https://raw.githubusercontent.com/srinijadharani/GitHub-Campus-Code-of-Conduct/main/github_landscape.png)

# Numpy

### What is Numpy?
NumPy is an open-source Python package. It stands for **Numerical Python**. It is a library consisting of multidimensional array objects and a collection of routines for processing of array. Using NumPy, mathematical and logical operations on arrays can be performed.

Check out Numpy's repository on GitHub [here](https://github.com/numpy/numpy)

### Installation:
- If you use pip, install Numpy using the following command:<br>
`pip install numpy`
- If you installed Anaconda, then Numpy comes pre-installed.

### Why use Numpy?
NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

### Importing:
You can import Numpy in your program using the following command: <br>
`import numpy as np`

In [1]:
import numpy as np

Check the version of Numpy you're using right now:

In [2]:
np.__version__

'1.20.3'

See the configuration of Numpy you're using right now:

In [3]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/srini/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/srini/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/srini/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/srini/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/srini/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/srini/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/srini/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/srini/anaconda3\\Library\\include']


### How can you create a Numpy Array?<br>
We can directly create a Numpy Array by converting a list or a list of lists:

In [4]:
list1 = [1, 6, "numpy", 9.7] # simple Python list
# converting this list into a Numpy array
np.array(list1)

array(['1', '6', 'numpy', '9.7'], dtype='<U32')

In [5]:
matrix1 = [[1, 2, 3], ["four", "five", "six"], [7.8, 9.0, 10.1]]
# we can even convert a list of lists (a matrix) into a numpy array
np.array(matrix1)

array([['1', '2', '3'],
       ['four', 'five', 'six'],
       ['7.8', '9.0', '10.1']], dtype='<U32')

**Note:** If you're wondering what '<U32' means:<br>
<: little endian - specifies the byte order<br>
U: Unicode string<br>
32: a string of 32 characters<br>
So, `dtype='<U32'` means a little-endian Unicode string of 32 characters.

You can also create a numpy array using the following functions:

In [6]:
np.arange(0, 10)
# arange() creates an array of evenly spaced values within a given interval

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

`arange()` works similar to the `range()` function in Python. You can even add a step as one of the parameters.<br>
Syntax:
`arange(start, stop, step)`

In [8]:
np.arange(1, 11, 2)
# creates an array of odd numbers between 1 and 11 (1 inclusive, 11 exclusive)

array([1, 3, 5, 7, 9])

In [9]:
np.arange(2, 11, 2)
# creates an array of even nuumbers between 2 and 11 (2 inclusive, 11 exclusive)

array([ 2,  4,  6,  8, 10])

You can create an array of zeros using the `zeros()` function.<br>
Syntax: `zeros(n)` or `zeros((n, m))`. 'n and m' are the number of zeros you want in your array. Using n alone would return a 1D array. (n, m) returns a 2D array of zeros.

**Note:** Remember to pass (n, m) as a tuple.

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Similar to zeros(), there is ones(). This function is used to create a 1D or 2D array of ones.

In [13]:
np.ones(2)

array([1., 1.])

In [14]:
np.ones((3, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

To find the memory size of a numpy array, use the following formula:<br>
`Memory size = size of the array * size of the items in the array`

In [16]:
arr = np.arange(1, 12)
print("%d bytes" %(arr.size * arr.itemsize))

44 bytes


In [17]:
arr.size

11

In [18]:
arr.itemsize

4

In [19]:
arr1 = np.array(["one", "two", "three", "four"])

In [20]:
arr1.size

4

In [21]:
arr1.itemsize

20

To create an array of **evenly spaced integers** over a specified interval, use the `linspace()` function.

In [22]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [24]:
np.linspace(0, 200, 10)

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

The `eye()` function is used to create an identity matrix of a given size.

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Numpy has the **random** module which has a lot of useful functions.

**Note:** Random number does not mean a different number every time. Random means something that can not be predicted logically.

`rand(x)` or `rand(x, y)` - creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1)

In [27]:
np.random.rand(10)

array([0.90686041, 0.68339155, 0.25263953, 0.52888379, 0.6522411 ,
       0.08040521, 0.95468398, 0.764556  , 0.21074499, 0.78057812])

In [28]:
np.random.rand(4, 4)
# rand - uniform distribution

array([[0.53073878, 0.2884517 , 0.65916252, 0.22842514],
       [0.03030595, 0.30790469, 0.15688523, 0.95489973],
       [0.4205393 , 0.27544475, 0.18495732, 0.08423577],
       [0.26796152, 0.49485765, 0.32901431, 0.06760323]])

`randn(x)` or `randn(x, y)` - returns an array from the standard normal distribution.

In [29]:
np.random.randn()
# one value

0.7708972375694806

In [30]:
np.random.randn(4)
# 4 values

array([ 0.10344622, -1.55634666, -0.33777462, -0.42138101])

In [31]:
np.random.randn(4, 3)
# a matrix of size 4, 3

array([[-0.11432184, -0.47291981,  0.06279605],
       [-1.18945243, -0.90578155, -1.61738795],
       [ 0.45875176,  0.52117105,  0.99144616],
       [ 0.24096445,  0.76590718, -0.31749352]])

`randint()` - returns random integers over the given range and if specified the number of integers

In [32]:
np.random.randint(1, 100)
# one integer

19

In [33]:
np.random.randint(1, 50, 10)
# n integers in a given interval

array([39, 16, 10, 39, 12, 18, 18, 38, 24, 46])

`reshape()` - gives a new shape to an array without changing its data.

In [34]:
arr2 = np.arange(1, 11)

In [35]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr2.reshape((2, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

To find the maximum in an array, use `max()`<br>
To find the minimum in an array, use `min()`<br>
To find the index of the maximum in an array, use `argmax()`<br>
To find the index of the minimum in an array, use `argmin()`<br>

In [37]:
arr3 = np.random.randint(1, 100, 10)

In [38]:
arr3

array([52,  6, 69, 27, 64, 82, 92, 33, 94, 33])

In [39]:
arr3.max()

94

In [40]:
arr3.argmax()

8

In [41]:
arr3.min()

6

In [42]:
arr3.argmin()

1

To check the shape of an array, use the `shape` attribute<br>
**Note**: `shape` is an attribute, not a function.

In [43]:
arr3.shape

(10,)

In [44]:
# Notice the two sets of brackets
arr.reshape(1, 11)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [45]:
arr.reshape(1, 11).shape

(1, 11)

In [46]:
arr.reshape(11, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Check the type of the elements in an array using `dtype` attribute:

In [48]:
arr.dtype

dtype('int32')

In [49]:
arr1

array(['one', 'two', 'three', 'four'], dtype='<U5')

In [50]:
arr1.dtype

dtype('<U5')

In [51]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr2.dtype

dtype('int32')

In [53]:
arr3

array([52,  6, 69, 27, 64, 82, 92, 33, 94, 33])

In [54]:
arr3.dtype

dtype('int32')

# Indexing and Slicing

In [55]:
arr = np.arange(0, 11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

To extract a part of an array, use the slice `[n:m]` operator.

In [57]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [58]:
arr[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

To make a copy of an existing array, use the `copy()` function.

In [61]:
arr_copy = arr.copy()

In [62]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr_copy[:] = 100

In [64]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr_2d = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))

In [67]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
#Indexing row
arr_2d[1]

array([4, 5, 6])

To index a 2d array, the format is `arr_2d[row][col]` or `arr_2d[row, col]`

In [69]:
arr_2d[1][0]

4

In [70]:
arr_2d[1,0]

4

In [71]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [72]:
arr_2d[2,:]

array([7, 8, 9])

To select a few elements from a numpy array, use relational operators or logical operators for instance. You can give your own conditions if you want.

In [73]:
arr = np.arange(1,11)

In [74]:
arr = np.arange(1,11)

In [75]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr > 7

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [77]:
dup_arr = arr > 7

In [78]:
arr[dup_arr]

array([ 8,  9, 10])

In [79]:
dup_arr

array([False, False, False, False, False, False, False,  True,  True,
        True])

Numpy supports a lot of arithmetic operations. For example:

In [80]:
arr = np.arange(0, 10)

In [81]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [83]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [85]:
arr / arr

C:\Users\srini\AppData\Local\Temp/ipykernel_116188/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [87]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [88]:
arr * 4

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [89]:
1 / arr

C:\Users\srini\AppData\Local\Temp/ipykernel_116188/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [90]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [91]:
# calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [92]:
np.max(arr)

9

In [93]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [94]:
np.log(arr)

C:\Users\srini\AppData\Local\Temp/ipykernel_116188/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

To find the sum of all elements in an array, use the `sum()` function

In [95]:
arr.sum()

45

In [96]:
matrix2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [97]:
matrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
matrix2.sum(axis = 0)

array([12, 15, 18])

In [99]:
matrix2.sum(axis = 1)

array([ 6, 15, 24])

To find the standard deviation of all elements in an array, use the `std()` function

In [100]:
arr.std()

2.8722813232690143

**References:**<br>
1. https://www.mygreatlearning.com/blog/python-numpy-tutorial/ - mygreatlearning
2. https://numpy.org/devdocs/user/absolute_beginners.html#:~:text=Why%20use%20NumPy%3F,of%20specifying%20the%20data%20types.

# the end.